### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by tiendungitd** [cloudbees/jnlp-slave-with-java-build-tools-dockerfile#11]
Hi, 
I'm using your image, but I got this issue, can you advise me how to fix it. Thanks.
/opt/bin/entry_point.sh: line 30: /usr/local/bin/jenkins-slave: Permission denied
/opt/bin/entry_point.sh: line 30: exec: /usr/local/bin/jenkins-slave: cannot execute: Permission denied

**Comment by karthik-ir** [comment]
I have permission issues when using persistent volume claims, the image not able to create the folders within. 
Reference [THIS ](https://github.com/fabric8io/jenkins-docker/issues/110#issuecomment-278719656)
