### ISSUE TITLE
Fatal error: Unable to find local grunt

### ISSUE THREAD

**Issue by Zer0-bit** [cloudbees/jnlp-slave-with-java-build-tools-dockerfile#14]
Hi - it would be helpful if local grunt could be installed somehow, as it's expected to exist as a reference in :

>  /home/jenkins/workspace/project-directory/package.json

 then it should be installed running the command "npm install" , but it can't be installed locally due to permission issues.
Other than this I find this image a lifesaver in a lot of situations due to it's extensive tools inclusion.

**Comment by richbg** [comment]
grunt is included in the existing images.
